name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        cxx: [g++, clang++]
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -q --build-arg cxx=$CXX -t blobdrop .
    - name: Format code
      run: docker run blobdrop sh -c 'scripts/format-code.sh'
    - name: Run tests
      run: docker run blobdrop sh -c 'QT_QPA_PLATFORM=offscreen ctest --test-dir build --output-on-failure'
    - name: Build documentation
      run: docker run blobdrop sh -c 'cd doc && doxygen'
